In [1]:
import numpy as np

Задание №1

In [18]:
N = int (input ("Пожалуйста укажите количество элементов: "))
np.arange (N-1, -1, -1)

Пожалуйста укажите количество элементов: 10


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

Задание №2

In [24]:
M = int (input ("Пожалуйста укажите количество элементов: "))
diag_1 = np.diag(np.arange(M-1, -1, -1))
print (diag_1)
print ("Сумма элементов по диагонали:", np.trace(diag_1))

Пожалуйста укажите количество элементов: 10
[[9 0 0 0 0 0 0 0 0 0]
 [0 8 0 0 0 0 0 0 0 0]
 [0 0 7 0 0 0 0 0 0 0]
 [0 0 0 6 0 0 0 0 0 0]
 [0 0 0 0 5 0 0 0 0 0]
 [0 0 0 0 0 4 0 0 0 0]
 [0 0 0 0 0 0 3 0 0 0]
 [0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0]]
Сумма элементов по диагонали: 45


Задание №3
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [25]:
a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4,] ] )
b = np.array( [4, 12, -3] )
from numpy import linalg
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

Задание №4
Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [28]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [30]:
def cosine( a, b ):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    
    # длины векторов
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    
    return np.dot( a, b ) / ( aLength * bLength )

In [41]:
print (cosine( users_stats, next_user_stats ))
val_max = 0
index = 0
users_list = []
for i in cosine( users_stats, next_user_stats ):
    if i > val_max:
        val_max = i
for i in cosine( users_stats, next_user_stats ):
    index +=1
    if val_max == i:
        users_list.append(index)
print ("Пользователи: ", *users_list, " наиболее похожи на нового пользователя. Значение косинусного сходства:", val_max)

[0.04688072 0.23440362 0.09376145 0.23440362 0.09376145 0.
 0.         0.14064217 0.         0.        ]
Пользователи:  2 4  наиболее похожи на нового пользователя. Значение косинусного сходства: 0.2344036154692477
